version: '3.9'

networks:
    api-network:
        driver: bridge

services:
    app:
        image: ${DOCKER_REGISTRY-}app
        container_name: api
        build:
            context: .
            dockerfile: vogue-decor.API/Dockerfile
        ports:
            - "7217:7216"
        networks:
            - api-network
        depends_on:
            - postgres_db
        environment:
            JWT:SecretKey: $JWT_SecretKey
            JWT:Issuer: $JWT_Issuer
            JWT:Audience: $JWT_Audience
            ConnectionStrings:PostgreSQL: $ConnectionString
            SMTP:Name: $SMTP_Name
            SMTP:Username: $SMTP_Username
            SMTP:Password: $SMTP_Password
            SMTP:Port: $SMTP_Port
            SMTP:Host: $SMTP_Host
            SMTP:Domain: $SMTP_Domain
            SMTP:UseSSL: $SMTP_UseSSL
            ASPNETCORE_Kestrel__Certificates__Default__Path: $ASPNETCORE_Kestrel__Certificates__Default__Path
            ASPNETCORE_Kestrel__Certificates__Default__Password: $ASPNETCORE_Kestrel__Certificates__Default__Password
        volumes:
            - /root/backend/vogue-decor/vogue-decor.API/wwwroot:/app/wwwroot
            - /toplight.pro.pfx:/app/toplight.pro.pfx
    
    postgres_db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        ports:
            - "5434:5432"
        networks:
            - api-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
    app:
